apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-builder-backend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: formbuilder
  template:
    metadata:
      labels:
        app: formbuilder
    spec:
      containers:
      - name: form-builder-backend
        image: nginx:1.14.2
        ports:
        - containerPort: 5000
        envFrom:
          - secretRef:
              name: formbuilder-secrets
        readinessProbe:
            httpGet:
              path: /health
              port: 5000
