apiVersion: v1
kind: Service
metadata:
  name: FormBuilder-service
spec:
  type: LoadBalancer
  selector:
    app: FormBuilder
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000