apiVersion: v1
kind: Service
metadata:
  name: formbuilder-service
spec:
  type: LoadBalancer
  selector:
    app: formbuilder
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000